### ISSUE TITLE
beep control 5v issue 

### ISSUE THREAD

**Issue by cyptus** [alperenguman/rpi-wiegand-reader#1]
@alperenguman why is beep control, which is in non-beep state a 5V high, directly connected to GPIO?
Wouldn‘t this damage the GPIO on the pi?

**Comment by alperenguman** [comment]
@cyptus Thank you for raising the issue. This project was 2 years ago so I'd be lying if I said I remember the specs but always use a multimeter to verify the incoming voltage, and down regulate anything above 3.3V for the RPi GPIO. I wanna give myself the benefit of the doubt and say that I verified and hence bypassed the regulator but it is equally possible that I had a brain fart.
